# Generated by Django 2.2.3 on 2019-07-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='amount_raised',
            field=models.IntegerField(default=0),
        ),
    ]
