# Generated by Django 2.2.3 on 2019-07-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0002_fundrequest_amount_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='percentage_raised',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='How_much_do_you_need',
            field=models.IntegerField(default=0),
        ),
    ]
