# Generated by Django 2.2.3 on 2019-09-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0003_auto_20190731_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
