# Generated by Django 2.2.3 on 2019-09-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0004_fundrequest_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_request_count', models.IntegerField(default=0)),
                ('total_amount_raised', models.IntegerField(default=0)),
                ('fully_funded', models.IntegerField(default=0)),
            ],
        ),
    ]
