# Generated by Django 2.2.3 on 2019-09-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0005_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='fully_funded',
            field=models.IntegerField(default=131),
        ),
        migrations.AlterField(
            model_name='village',
            name='fund_request_count',
            field=models.IntegerField(default=429),
        ),
        migrations.AlterField(
            model_name='village',
            name='total_amount_raised',
            field=models.IntegerField(default=6691263),
        ),
    ]
