# Generated by Django 2.2 on 2020-10-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('subdomain_prefix', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='organizations/logos')),
                ('account_name_alias', models.CharField(blank=True, help_text='Used on signup screen, typically specifies what the funding is for', max_length=40)),
                ('student_account_alias', models.CharField(blank=True, help_text='used in signup screens. should be prefixed with the appropriate a/an', max_length=40)),
                ('whatsapp_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('facebook', models.CharField(blank=True, max_length=400)),
                ('instagram', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organizations/carousels')),
                ('header', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=300)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousels', to='organizations.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='organizations/assets')),
                ('about_image_2', models.ImageField(blank=True, null=True, upload_to='organizations/assets')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='organizations.Organization')),
            ],
        ),
    ]
