# Generated by Django 2.2.3 on 2019-08-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('read', 'Can read'),)},
        ),
    ]
