# Generated by Django 2.2 on 2020-10-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('blog', '0002_auto_20190827_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_permissions': ('add',), 'permissions': (('read', 'Can read'),)},
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_category_organization', to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_organization', to='organizations.Organization'),
        ),
    ]
