# Generated by Django 2.2.3 on 2019-07-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
